package com.ossprj.commons.metadata.audio.model;

public enum TagName {

    // Performance Info
    AccurateRipDiscId,
    AccurateRipResult,
    Album,
    AlbumArtist,
    AnalogAudienceSource,
    AnalogSoundboardSource,
    AnalogLineage,
    AnalogSoundPreservation,
    Artist,
    AudioFileUrl,
    AudioSourceUrl,
    Band,
    BuyCdUrl,
    CatalogNumber,
    CodingHistory,
    Comment,
    Comments,
    Composer,
    Contact,
    Copyright,
    Creator,
    Date,
    Description,
    Disc,
    DiscId,
    DiscNumber,
    DiscTotal,
    EncodedBy,
    Encoder,
    EncoderSettings,
    Encoding,
    Engineer,
    Ensemble,
    Genre,
    Keywords,
    Label,
    Language,
    Length,
    Lineage,
    Location,
    Lyrics,
    Lyricist,
    MasteredBy,
    MasteringNotes,
    MatrixBy,
    Notes,
    Organization,
    OrigArtist,
    OrigDate,
    Originator,
    OrigTime,
    OriginalArtist,
    Performer,
    Producer,
    Publisher,
    Rating,
    RecordedBy,
    ReleaseDate,
    ReleaseNumber,
    ReplayGainAlbumGain,
    ReplayGainAlbumPeak,
    ReplayGainReferenceLoudness,
    ReplayGainTrackGain,
    ReplayGainTrackPeak,
    Set,
    SetNumber,
    ShnId,
    SoundboardSource,
    Source,
    SourceMedia,
    SourceMedium,
    TapedBy,
    TimeReference,
    Title,
    TotalDiscs,
    TotalTracks,
    TrackNumber,
    TrackNumberText,
    TrackTotal,
    TransferredBy,
    Url,
    Venue,
    Version,
    WaveFormatExtensibleChannelMask,
    Year,

    comment2,
    episodeid,
    ien,
    ieng,
    isft,
    mediumstockbrands,
    mood,
    spars,
    special,

    // wm/mcdi
    // mediajukebox:toolname
    // mediajukebox:toolversion

    ;



}
